services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
